TeduShop.Web/Controllers/ContactController.cs
using AutoMapper;
using BotDetect.Web.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using TeduShop.Common;
using TeduShop.Model.Models;
using TeduShop.Service;
using TeduShop.Web.Infrastructure.Extensions;
using TeduShop.Web.Models;

namespace TeduShop.Web.Controllers
{
    public class ContactController : Controller
    {
        IContactDetailService _contactDetailService;
        IFeedbackService _feedbackService;
        public ContactController(IContactDetailService contactDetailService, IFeedbackService feedbackService)
        {
            this._contactDetailService = contactDetailService;
            this._feedbackService = feedbackService;
        }
        // GET: Contact
        public ActionResult Index()
        {

            FeedbackViewModel viewModel = new FeedbackViewModel();
            viewModel.ContactDetail = GetDetail();
            return View(viewModel);
        }

        [HttpPost]
        [CaptchaValidation("CaptchaCode", "contactCaptcha", "Mã xác nhận không đúng")]
        public ActionResult SendFeedback(FeedbackViewModel feedbackViewModel)
        {
            if (ModelState.IsValid)
            {
                Feedback newFeedback = new Feedback();
                newFeedback.UpdateFeedback(feedbackViewModel);
                _feedbackService.Create(newFeedback);
                _feedbackService.Save();

                ViewData["SuccessMsg"] = "Gửi phản hồi thành công";


                string content = System.IO.File.ReadAllText(Server.MapPath("/Assets/client/template/contact_template.html"));
                content = content.Replace("{{Name}}", feedbackViewModel.Name);
                content = content.Replace("{{Email}}", feedbackViewModel.Email);
                content = content.Replace("{{Message}}", feedbackViewModel.Message);
                var adminEmail = ConfigHelper.GetByKey("AdminEmail");
                MailHelper.SendMail(adminEmail, "Thông tin liên hệ từ website", content);

                feedbackViewModel.Name = "";
                feedbackViewModel.Message = "";
                feedbackViewModel.Email = "";
            }
            feedbackViewModel.ContactDetail = GetDetail();


            return View("Index", feedbackViewModel);
        }

        private ContactDetailViewModel GetDetail()
        {
            var model = _contactDetailService.GetDefaultContact();
            var contactViewModel = Mapper.Map<ContactDetail, ContactDetailViewModel>(model);
            return contactViewModel;
        }
    }
}

TeduShop.Web/Views/Contact/Index.cshtml
@model TeduShop.Web.Models.FeedbackViewModel
@using BotDetect.Web.Mvc;
@{
    ViewBag.Title = "Liên hệ";
    Layout = "~/Views/Shared/Layouts.cshtml";
}
@section footerJS{
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAk3Eeu6MXm1Y6qil2hO6j89kckY5nnSTo"></script>
    <script src="~/Assets/client/js/controllers/contact.js"></script>
}
<style>
    #map {
        height: 400px;
    }
</style>
<link href="@BotDetect.Web.CaptchaUrls.Absolute.LayoutStyleSheetUrl" rel="stylesheet" type="text/css" />
<input type="hidden" id="hidAddress" value="@Model.ContactDetail.Name<br />Điện thoại:@Model.ContactDetail.Phone <br>Địa chỉ: @Model.ContactDetail.Address" />
<input type="hidden" id="hidLat" value="@Model.ContactDetail.Lat" />
<input type="hidden" id="hidLng" value="@Model.ContactDetail.Lng" />
<input type="hidden" id="hidName" value="@Model.ContactDetail.Name" />
<div class="main">
    <div class="reservation_top">
        <div class="contact_right">
            <h3>Thông tin liên hệ</h3>
            <address class="address">
                <p>@Model.ContactDetail.Address</p>
                <dl>
                    <dt> </dt>
                    <dd>Điện thoại:<span> @Model.ContactDetail.Phone</span></dd>
                    <dd>E-mail:&nbsp; <a href="mailto:@(Model.ContactDetail.Email)">@(Model.Email)</a></dd>
                </dl>
            </address>
            <div class="clearfix"></div>
            <div id="map"></div>
        </div>
    </div>

    <div class="reservation_top">
        <div class="contact_right">
            <h3>Gửi thông tin liên hệ</h3>
            <div class="contact-form">
                @using (Html.BeginForm("SendFeedback", "Contact", FormMethod.Post))
                {
                    if (ViewData["SuccessMsg"] != null)
                    {
                        <div class="alert alert-success" role="alert">
                            <strong>Chúc mừng bạn! </strong> gửi phản hồi thành công.
                            <br />Chúng tôi sẽ liên hệ lại sớm nhất có thể.
                        </div>
                    }
                    @Html.ValidationSummary(false, "", new { @class = "error" });
                    @Html.TextBoxFor(model => model.Name, new { @class = "textbox" });
                    @Html.TextBoxFor(model => model.Email, new { @class = "textbox" });
                    @Html.TextAreaFor(model => model.Message);


                    MvcCaptcha contactCaptcha = new MvcCaptcha("contactCaptcha");
                    @Html.Captcha(contactCaptcha)
                    @Html.TextBox("CaptchaCode")

                    <input type="submit" value="Gửi đi">
                    <div class="clearfix"> </div>
                }
            </div>
        </div>
    </div>
</div>